package com.bankteller.admin.queue;

public class QueueManagementUI extends javax.swing.JFrame {

    /**
     * Creates new form QueueManagementUI
     */
    public QueueManagementUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlQueueMgmt = new javax.swing.JPanel();
        tabCustomers = new javax.swing.JTabbedPane();
        pnlActive = new javax.swing.JPanel();
        scrllActive1 = new javax.swing.JScrollPane();
        tblActive1 = new javax.swing.JTable();
        scrllActive4 = new javax.swing.JScrollPane();
        tblActive4 = new javax.swing.JTable();
        scrllActive2 = new javax.swing.JScrollPane();
        tblActive2 = new javax.swing.JTable();
        scrllActive3 = new javax.swing.JScrollPane();
        tblActive3 = new javax.swing.JTable();
        scrllActive5 = new javax.swing.JScrollPane();
        tblActive5 = new javax.swing.JTable();
        pnlCompleted = new javax.swing.JPanel();
        scrllCompleted1 = new javax.swing.JScrollPane();
        tblCompleted1 = new javax.swing.JTable();
        scrllCompleted2 = new javax.swing.JScrollPane();
        tblCompleted2 = new javax.swing.JTable();
        scrllCompleted3 = new javax.swing.JScrollPane();
        tblCompleted3 = new javax.swing.JTable();
        scrllCompleted4 = new javax.swing.JScrollPane();
        tblCompleted4 = new javax.swing.JTable();
        scrllCompleted5 = new javax.swing.JScrollPane();
        tblCompleted5 = new javax.swing.JTable();
        pnlQueue = new javax.swing.JPanel();
        scrllQueue = new javax.swing.JScrollPane();
        tblQueue = new javax.swing.JTable();
        pnlDetails = new javax.swing.JPanel();
        lblName = new javax.swing.JLabel();
        lblTeller = new javax.swing.JLabel();
        lblService = new javax.swing.JLabel();
        lblQueue = new javax.swing.JLabel();
        lblStatus = new javax.swing.JLabel();
        chkEmergency = new javax.swing.JCheckBox();
        lblEmergency = new javax.swing.JLabel();
        btnReassign = new javax.swing.JButton();
        btnSkip = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlQueueMgmt.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Queue Management", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Yu Gothic", 3, 14))); // NOI18N

        tabCustomers.setFont(new java.awt.Font("Yu Gothic", 0, 12)); // NOI18N

        tblActive1.setFont(new java.awt.Font("Yu Gothic", 0, 12)); // NOI18N
        tblActive1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null}
            },
            new String [] {
                "Teller 1"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        scrllActive1.setViewportView(tblActive1);
        if (tblActive1.getColumnModel().getColumnCount() > 0) {
            tblActive1.getColumnModel().getColumn(0).setResizable(false);
        }

        tblActive4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null}
            },
            new String [] {
                "Teller 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        scrllActive4.setViewportView(tblActive4);
        if (tblActive4.getColumnModel().getColumnCount() > 0) {
            tblActive4.getColumnModel().getColumn(0).setResizable(false);
        }

        tblActive2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null}
            },
            new String [] {
                "Teller 2"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        scrllActive2.setViewportView(tblActive2);
        if (tblActive2.getColumnModel().getColumnCount() > 0) {
            tblActive2.getColumnModel().getColumn(0).setResizable(false);
        }

        tblActive3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null}
            },
            new String [] {
                "Teller 3"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        scrllActive3.setViewportView(tblActive3);
        if (tblActive3.getColumnModel().getColumnCount() > 0) {
            tblActive3.getColumnModel().getColumn(0).setResizable(false);
        }

        tblActive5.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null}
            },
            new String [] {
                "Teller 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        scrllActive5.setViewportView(tblActive5);
        if (tblActive5.getColumnModel().getColumnCount() > 0) {
            tblActive5.getColumnModel().getColumn(0).setResizable(false);
        }

        javax.swing.GroupLayout pnlActiveLayout = new javax.swing.GroupLayout(pnlActive);
        pnlActive.setLayout(pnlActiveLayout);
        pnlActiveLayout.setHorizontalGroup(
            pnlActiveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlActiveLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrllActive1, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(scrllActive2, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addComponent(scrllActive3, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(pnlActiveLayout.createSequentialGroup()
                .addGap(114, 114, 114)
                .addComponent(scrllActive4, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(scrllActive5, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlActiveLayout.setVerticalGroup(
            pnlActiveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlActiveLayout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addGroup(pnlActiveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrllActive1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(scrllActive2, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(scrllActive3, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlActiveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrllActive4, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(scrllActive5, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33))
        );

        tabCustomers.addTab("ACTIVE", pnlActive);

        tblCompleted1.setFont(new java.awt.Font("Yu Gothic", 0, 12)); // NOI18N
        tblCompleted1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Teller 1"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        scrllCompleted1.setViewportView(tblCompleted1);
        if (tblCompleted1.getColumnModel().getColumnCount() > 0) {
            tblCompleted1.getColumnModel().getColumn(0).setResizable(false);
        }

        tblCompleted2.setFont(new java.awt.Font("Yu Gothic", 0, 12)); // NOI18N
        tblCompleted2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Teller 2"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        scrllCompleted2.setViewportView(tblCompleted2);
        if (tblCompleted2.getColumnModel().getColumnCount() > 0) {
            tblCompleted2.getColumnModel().getColumn(0).setResizable(false);
        }

        tblCompleted3.setFont(new java.awt.Font("Yu Gothic", 0, 12)); // NOI18N
        tblCompleted3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Teller 3"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        scrllCompleted3.setViewportView(tblCompleted3);
        if (tblCompleted3.getColumnModel().getColumnCount() > 0) {
            tblCompleted3.getColumnModel().getColumn(0).setResizable(false);
        }

        tblCompleted4.setFont(new java.awt.Font("Yu Gothic", 0, 12)); // NOI18N
        tblCompleted4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Teller 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        scrllCompleted4.setViewportView(tblCompleted4);
        if (tblCompleted4.getColumnModel().getColumnCount() > 0) {
            tblCompleted4.getColumnModel().getColumn(0).setResizable(false);
        }

        tblCompleted5.setFont(new java.awt.Font("Yu Gothic", 0, 12)); // NOI18N
        tblCompleted5.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Teller 5"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        scrllCompleted5.setViewportView(tblCompleted5);
        if (tblCompleted5.getColumnModel().getColumnCount() > 0) {
            tblCompleted5.getColumnModel().getColumn(0).setResizable(false);
        }

        javax.swing.GroupLayout pnlCompletedLayout = new javax.swing.GroupLayout(pnlCompleted);
        pnlCompleted.setLayout(pnlCompletedLayout);
        pnlCompletedLayout.setHorizontalGroup(
            pnlCompletedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCompletedLayout.createSequentialGroup()
                .addContainerGap(51, Short.MAX_VALUE)
                .addComponent(scrllCompleted1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrllCompleted2, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrllCompleted3, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrllCompleted4, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrllCompleted5, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53))
        );
        pnlCompletedLayout.setVerticalGroup(
            pnlCompletedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCompletedLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlCompletedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(scrllCompleted2, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                    .addComponent(scrllCompleted1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(scrllCompleted3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                    .addComponent(scrllCompleted4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                    .addComponent(scrllCompleted5, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE))
                .addContainerGap())
        );

        tabCustomers.addTab("COMPLETED", pnlCompleted);

        pnlQueue.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Queue", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Yu Gothic", 2, 12))); // NOI18N

        tblQueue.setFont(new java.awt.Font("Yu Gothic", 0, 12)); // NOI18N
        tblQueue.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Teller No.", "Queue No.", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        scrllQueue.setViewportView(tblQueue);
        if (tblQueue.getColumnModel().getColumnCount() > 0) {
            tblQueue.getColumnModel().getColumn(0).setResizable(false);
            tblQueue.getColumnModel().getColumn(0).setPreferredWidth(5);
            tblQueue.getColumnModel().getColumn(1).setResizable(false);
            tblQueue.getColumnModel().getColumn(1).setPreferredWidth(10);
            tblQueue.getColumnModel().getColumn(2).setResizable(false);
        }

        javax.swing.GroupLayout pnlQueueLayout = new javax.swing.GroupLayout(pnlQueue);
        pnlQueue.setLayout(pnlQueueLayout);
        pnlQueueLayout.setHorizontalGroup(
            pnlQueueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlQueueLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(scrllQueue, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(173, 173, 173))
        );
        pnlQueueLayout.setVerticalGroup(
            pnlQueueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlQueueLayout.createSequentialGroup()
                .addComponent(scrllQueue, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlDetails.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Customer Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Yu Gothic", 2, 12))); // NOI18N

        lblName.setFont(new java.awt.Font("Yu Gothic", 3, 14)); // NOI18N
        lblName.setText("Customer Name:");

        lblTeller.setFont(new java.awt.Font("Yu Gothic", 3, 14)); // NOI18N
        lblTeller.setText("Assigned Teller:");

        lblService.setFont(new java.awt.Font("Yu Gothic", 3, 14)); // NOI18N
        lblService.setText("Requested Service:");

        lblQueue.setFont(new java.awt.Font("Yu Gothic", 3, 14)); // NOI18N
        lblQueue.setText("Queue No.:");

        lblStatus.setFont(new java.awt.Font("Yu Gothic", 3, 14)); // NOI18N
        lblStatus.setText("Status:");

        chkEmergency.setFont(new java.awt.Font("Yu Gothic", 2, 14)); // NOI18N
        chkEmergency.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        chkEmergency.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        chkEmergency.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        chkEmergency.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkEmergencyActionPerformed(evt);
            }
        });

        lblEmergency.setFont(new java.awt.Font("Yu Gothic", 3, 14)); // NOI18N
        lblEmergency.setText("Emergency?");

        btnReassign.setFont(new java.awt.Font("Yu Gothic", 0, 12)); // NOI18N
        btnReassign.setText("REASSIGN");

        btnSkip.setFont(new java.awt.Font("Yu Gothic", 0, 12)); // NOI18N
        btnSkip.setText("SKIP");

        jLabel1.setFont(new java.awt.Font("Yu Gothic", 0, 14)); // NOI18N
        jLabel1.setText("0");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel2.setFont(new java.awt.Font("Yu Gothic", 0, 14)); // NOI18N
        jLabel2.setText("Teller");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel3.setFont(new java.awt.Font("Yu Gothic", 0, 14)); // NOI18N
        jLabel3.setText("Name");
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel4.setFont(new java.awt.Font("Yu Gothic", 0, 14)); // NOI18N
        jLabel4.setText("Deposit");
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel5.setFont(new java.awt.Font("Yu Gothic", 0, 14)); // NOI18N
        jLabel5.setText("Queued");
        jLabel5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout pnlDetailsLayout = new javax.swing.GroupLayout(pnlDetails);
        pnlDetails.setLayout(pnlDetailsLayout);
        pnlDetailsLayout.setHorizontalGroup(
            pnlDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDetailsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDetailsLayout.createSequentialGroup()
                        .addGroup(pnlDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblEmergency, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblService, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblStatus, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlDetailsLayout.createSequentialGroup()
                                .addComponent(lblTeller, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(24, 24, 24)))
                        .addGap(18, 18, 18)
                        .addGroup(pnlDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlDetailsLayout.createSequentialGroup()
                                .addComponent(chkEmergency, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDetailsLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(pnlDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDetailsLayout.createSequentialGroup()
                                .addComponent(lblQueue, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDetailsLayout.createSequentialGroup()
                                .addComponent(btnReassign)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnSkip)))))
                .addContainerGap())
        );
        pnlDetailsLayout.setVerticalGroup(
            pnlDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDetailsLayout.createSequentialGroup()
                .addGroup(pnlDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblQueue)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(pnlDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTeller)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(pnlDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblName)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblService)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(pnlDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStatus)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(pnlDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chkEmergency)
                    .addComponent(lblEmergency))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(pnlDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnReassign)
                    .addComponent(btnSkip))
                .addContainerGap())
        );

        javax.swing.GroupLayout pnlQueueMgmtLayout = new javax.swing.GroupLayout(pnlQueueMgmt);
        pnlQueueMgmt.setLayout(pnlQueueMgmtLayout);
        pnlQueueMgmtLayout.setHorizontalGroup(
            pnlQueueMgmtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlQueueMgmtLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlQueueMgmtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tabCustomers)
                    .addGroup(pnlQueueMgmtLayout.createSequentialGroup()
                        .addComponent(pnlQueue, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnlDetails, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlQueueMgmtLayout.setVerticalGroup(
            pnlQueueMgmtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlQueueMgmtLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabCustomers, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlQueueMgmtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlDetails, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlQueue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(11, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlQueueMgmt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlQueueMgmt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chkEmergencyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkEmergencyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkEmergencyActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QueueManagementUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QueueManagementUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QueueManagementUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QueueManagementUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QueueManagementUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnReassign;
    private javax.swing.JButton btnSkip;
    private javax.swing.JCheckBox chkEmergency;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lblEmergency;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblQueue;
    private javax.swing.JLabel lblService;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JLabel lblTeller;
    private javax.swing.JPanel pnlActive;
    private javax.swing.JPanel pnlCompleted;
    private javax.swing.JPanel pnlDetails;
    private javax.swing.JPanel pnlQueue;
    private javax.swing.JPanel pnlQueueMgmt;
    private javax.swing.JScrollPane scrllActive1;
    private javax.swing.JScrollPane scrllActive2;
    private javax.swing.JScrollPane scrllActive3;
    private javax.swing.JScrollPane scrllActive4;
    private javax.swing.JScrollPane scrllActive5;
    private javax.swing.JScrollPane scrllCompleted1;
    private javax.swing.JScrollPane scrllCompleted2;
    private javax.swing.JScrollPane scrllCompleted3;
    private javax.swing.JScrollPane scrllCompleted4;
    private javax.swing.JScrollPane scrllCompleted5;
    private javax.swing.JScrollPane scrllQueue;
    private javax.swing.JTabbedPane tabCustomers;
    private javax.swing.JTable tblActive1;
    private javax.swing.JTable tblActive2;
    private javax.swing.JTable tblActive3;
    private javax.swing.JTable tblActive4;
    private javax.swing.JTable tblActive5;
    private javax.swing.JTable tblCompleted1;
    private javax.swing.JTable tblCompleted2;
    private javax.swing.JTable tblCompleted3;
    private javax.swing.JTable tblCompleted4;
    private javax.swing.JTable tblCompleted5;
    private javax.swing.JTable tblQueue;
    // End of variables declaration//GEN-END:variables
}
