/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.example.bankqueuesystem;

import java.awt.Color;

/**
 *
 * @author HOME
 */
public class AdminDashboard extends javax.swing.JFrame {

    /**
     * Creates new form dashboard
     */
    public AdminDashboard() {
        initComponents();
        simulateDashboardStats(); // Call method after GUI loads
    }
    
    private void simulateDashboardStats() {
        new javax.swing.Timer(5000, evt -> {
            int peopleInQueue = (int) (Math.random() * 10); // 0–9
            int activeTellers = (int) (Math.random() * 4);   // 0–3
            int waitMinutes = (int) (Math.random() * 10);    // 0–9 min
            int waitSeconds = (int) (Math.random() * 60);

            String formattedWait = String.format("%02d:%02d", waitMinutes, waitSeconds);

            // Update UI components
            lblPeopleInQueue.setText(String.valueOf(peopleInQueue));
            lblActiveTellers.setText(String.valueOf(activeTellers));
            lblLongestWait.setText(formattedWait);
        }).start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        AdminDashboardTitle = new javax.swing.JLabel();
        navPanel = new javax.swing.JPanel();
        btnServiceConfiguration = new javax.swing.JButton();
        btnTellerManagement = new javax.swing.JButton();
        btnReportsAndAnalytics = new javax.swing.JButton();
        btnQueueManagement = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        titlePeopleInQueue = new javax.swing.JLabel();
        titleActiveTellers = new javax.swing.JLabel();
        titleLongestWait = new javax.swing.JLabel();
        lblPeopleInQueue = new javax.swing.JLabel();
        lblActiveTellers = new javax.swing.JLabel();
        lblLongestWait = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new Color(245, 245, 245));

        jPanel2.setBackground(new Color(38, 50, 56));

        AdminDashboardTitle.setBackground(new Color(245, 245, 245));
        AdminDashboardTitle.setFont(new java.awt.Font("Script MT Bold", 1, 48)); // NOI18N
        AdminDashboardTitle.setForeground(new Color(245, 245, 245));
        AdminDashboardTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AdminDashboardTitle.setText("Admin Dashboard");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(223, 223, 223)
                .addComponent(AdminDashboardTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(AdminDashboardTitle)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        navPanel.setBackground(new Color(207, 216, 220));

        btnServiceConfiguration.setBackground(new Color(186, 104, 200));
        btnServiceConfiguration.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        btnServiceConfiguration.setText("🔧 Service Configuration");
        btnServiceConfiguration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnServiceConfigurationActionPerformed(evt);
            }
        });

        btnTellerManagement.setBackground(new Color(100, 181, 246));
        btnTellerManagement.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        btnTellerManagement.setText("⚙ Teller Management");
        btnTellerManagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTellerManagementActionPerformed(evt);
            }
        });

        btnReportsAndAnalytics.setBackground(new Color(255, 202, 58));
        btnReportsAndAnalytics.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        btnReportsAndAnalytics.setText("📊 Reports & Analytics");
        btnReportsAndAnalytics.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportsAndAnalyticsActionPerformed(evt);
            }
        });

        btnQueueManagement.setBackground(new Color(129, 199, 132));
        btnQueueManagement.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        btnQueueManagement.setText("🔁 Queue Management");
        btnQueueManagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQueueManagementActionPerformed(evt);
            }
        });

        btnLogout.setBackground(new Color(255, 87, 87));
        btnLogout.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        btnLogout.setText("LOGOUT");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout navPanelLayout = new javax.swing.GroupLayout(navPanel);
        navPanel.setLayout(navPanelLayout);
        navPanelLayout.setHorizontalGroup(
            navPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(navPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(navPanelLayout.createSequentialGroup()
                        .addGroup(navPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnTellerManagement, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnServiceConfiguration))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(btnReportsAndAnalytics, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnQueueManagement, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(navPanelLayout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addComponent(btnLogout)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        navPanelLayout.setVerticalGroup(
            navPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navPanelLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(btnTellerManagement, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnServiceConfiguration)
                .addGap(18, 18, 18)
                .addComponent(btnReportsAndAnalytics, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnQueueManagement, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(btnLogout)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        titlePeopleInQueue.setFont(new java.awt.Font("Rockwell Condensed", 1, 18)); // NOI18N
        titlePeopleInQueue.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titlePeopleInQueue.setText("People in Queue");

        titleActiveTellers.setFont(new java.awt.Font("Rockwell Condensed", 1, 18)); // NOI18N
        titleActiveTellers.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleActiveTellers.setText("Active Tellers");

        titleLongestWait.setFont(new java.awt.Font("Rockwell Condensed", 1, 18)); // NOI18N
        titleLongestWait.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLongestWait.setText("Longest Wait Time");

        lblPeopleInQueue.setFont(new java.awt.Font("Rockwell", 0, 36)); // NOI18N
        lblPeopleInQueue.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPeopleInQueue.setText("loading..");

        lblActiveTellers.setFont(new java.awt.Font("Rockwell", 0, 36)); // NOI18N
        lblActiveTellers.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblActiveTellers.setText("loading..");

        lblLongestWait.setFont(new java.awt.Font("Rockwell", 0, 36)); // NOI18N
        lblLongestWait.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLongestWait.setText("loading..");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(navPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(titlePeopleInQueue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblPeopleInQueue, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(titleActiveTellers, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblActiveTellers, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(titleLongestWait, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblLongestWait, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(titlePeopleInQueue, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(titleActiveTellers, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(titleLongestWait, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(50, 50, 50)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPeopleInQueue, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblActiveTellers, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblLongestWait, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(navPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTellerManagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTellerManagementActionPerformed
        new TellerManagement().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnTellerManagementActionPerformed

    private void btnServiceConfigurationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnServiceConfigurationActionPerformed
        new ServiceConfiguration().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnServiceConfigurationActionPerformed

    private void btnReportsAndAnalyticsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportsAndAnalyticsActionPerformed
        new ReportsAndAnalytics().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnReportsAndAnalyticsActionPerformed

    private void btnQueueManagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQueueManagementActionPerformed
        new QueueManagement().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnQueueManagementActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        this.dispose(); // Close AdminDashboard
    }//GEN-LAST:event_btnLogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AdminDashboardTitle;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnQueueManagement;
    private javax.swing.JButton btnReportsAndAnalytics;
    private javax.swing.JButton btnServiceConfiguration;
    private javax.swing.JButton btnTellerManagement;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblActiveTellers;
    private javax.swing.JLabel lblLongestWait;
    private javax.swing.JLabel lblPeopleInQueue;
    private javax.swing.JPanel navPanel;
    private javax.swing.JLabel titleActiveTellers;
    private javax.swing.JLabel titleLongestWait;
    private javax.swing.JLabel titlePeopleInQueue;
    // End of variables declaration//GEN-END:variables
}
